# Generated by Django 6.0.1 on 2026-01-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paperskill", "0004_course_price"),
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="completed_courses",
            field=models.ManyToManyField(blank=True, related_name="completed", to="paperskill.course"),
        ),
    ]
