# Generated by Django 6.0.1 on 2026-01-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperskill', '0002_alter_course_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Платный курс'),
        ),
    ]
